---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nookpost
  namespace: nookpost
spec:
  hosts:
  - "nookpost-dev.jkulzer.dev"
  gateways:
  - istio-system/main-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1
    - uri:
        prefix: /swagger
    route:
    - destination:
        host: backend
        port:
          number: 5000
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 80
