services:
  frontend:
    build:
      context: ../nookpost-frontend/.
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://localhost:8080
    networks:
      - nookpost
  backend:
    build:
      context: ../nookpost-backend/.
      dockerfile: Dockerfile
    networks:
      - nookpost
  proxy:
    ports:
      - 8080:80
    image: nginx:1.27.4
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - nookpost
networks:
  nookpost:
