---
apiVersion: v1
kind: Secret
metadata:
  name: nookpost-infra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/nookpost/nookpost-infra.git
